In [305]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as linalg
%matplotlib inline

# Practica 1
La practica consiste de una introduccion a la asignatura de reconocimiento de patrones.

### 1. Basicos

In [8]:
# Declaracion de un arreglo bidimensional
A = [[1,2,3],
     [4,5,6],
     [7,8,9]]
A = np.array(A)
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 2. Tipos basicos

#### A. Escalares, vectores y matrices

In [52]:
A = np.array([[1,0],
              [0,1]])              # Matriz 2x2
n = 5                              # Escalar

In [231]:
# Vector renglon
vr = np.array([[1,2,3]])              

print("Vector renglon:\n")
print(vr)
print("\nDimension: ", vr.shape)

Vector renglon:

[[1 2 3]]

Dimension:  (1, 3)


In [50]:
# Vector columna
vc = np.array([[1], 
               [2],
               [3]])

print("\nVector columna:\n")
print(vc)
print("\nDimension: ", vc.shape)


Vector columna:

[[1]
 [2]
 [3]]

Dimension:  (3, 1)


In [232]:
# Transpuesta de un vector
print("\nDimensiones vc a vr: ", vc.transpose().shape)
print("\nDimensiones vr a vc: ", vr.transpose().shape)


Dimensiones vc a vr:  (1, 3)

Dimensiones vr a vc:  (3, 1)


In [56]:
# Vector en un rango de numeros especifico (exclusivo)
v = np.arange(1,10)                    # Metodo 1 -> arange()
v1 = np.linspace(1,10,20)              # Metodo 2 -> linspace() 
print("\nVECTOR RANGO M1: ")
print(v)
print("\nVECTOR RANGO M2: ")
print(v1)


VECTOR RANGO M1: 
[1 2 3 4 5 6 7 8 9]

VECTOR RANGO M2: 
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


#### B. Creacion de matrices especiales

In [72]:
m1 = np.zeros((3,3))             # Matriz de ceros   (renglones, columnas)
m2 = np.ones((3,3))              # Matriz de unos    (renglones, columnas)
m3 = np.eye(3)                   # Matriz identidad
m4 = np.random.rand(3,3)         # Matriz aleatoria  (renglones, columnas)

print("Matriz de ceros:\n")
print(m1)
print("\nMatriz de unos:\n")
print(m2)
print("\nMatriz identidad:\n")
print(m3)
print("\nMatriz aleatoria:\n")
print(m4)

Matriz de ceros:

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz de unos:

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriz identidad:

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz aleatoria:

[[0.58542607 0.88766143 0.5157679 ]
 [0.68192022 0.63668578 0.71177212]
 [0.8831329  0.52988192 0.49922324]]


#### C. Indices en vectores y matrices

In [115]:
v = np.arange(1,10)
m = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

print("Vector: ")
print(v)
print("\nMatriz")
print(m)

Vector: 
[1 2 3 4 5 6 7 8 9]

Matriz
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
print(v[0])                       # Acceder a un elemento del vector

1


In [116]:
print(m[0,1])                     # Acceder a un elemento de la matriz

2


In [117]:
print(m[0,:])                     # Acceder a un renglon de la matriz (primero)

[1 2 3 4]


In [118]:
print(m[:,1])                     # Acceder a una columna de la matriz (segunda)

[ 2  6 10]


In [119]:
print(m[1,0:2])                   # Acceder a los primeros dos elementos del renglon 1

[5 6]


In [120]:
print(m[0:2,2])                   # Acceder a los primeros dos elementos de la columna 3

[3 7]


In [121]:
print(m[1:,2])                    # Acceder a los ultimos elementos de la columna 3

[ 7 11]


In [125]:
print("Filas: ", m.shape[0])      # Numero de filas
print("Columnas: ", m.shape[1])   # Numero de columnas

Filas:  3
Columnas:  4


In [129]:
mNew = np.zeros(m.shape)          # Crear matrix con las dimensiones de m 
print(mNew)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [131]:
type(m)                            # Obtener informacion del tipo de dato

numpy.ndarray

### 3. Operaciones simples con vectores y matrices

#### A. Operaciones elemento a elemento

In [204]:
a = np.array([1,2,3,4]).transpose()   # Vector columna 1
a.shape = (4, 1)

b = np.array([5,6,7,7]).transpose()   # Vector columna 2
b.shape = (4, 1)

print("Vector a:")
print(a)
print("\nVector b:")
print(b)

Vector a:
[[1]
 [2]
 [3]
 [4]]

Vector b:
[[5]
 [6]
 [7]
 [7]]


In [149]:
2 * a                                 # Multiplicacion por un escalar

array([[2],
       [4],
       [6],
       [8]])

In [151]:
a / 4                                 # Division por un escalar

array([[0.25],
       [0.5 ],
       [0.75],
       [1.  ]])

In [172]:
a + b                                 # Suma de vectores
np.add(a, b)                                 

array([[ 6],
       [ 8],
       [10],
       [11]])

In [173]:
a - b                                 # Resta de vectores
np.subtract(a, b)

array([[-4],
       [-4],
       [-4],
       [-3]])

In [156]:
np.square(a)                          # Elevar al cuadrado 

array([[ 1],
       [ 4],
       [ 9],
       [16]])

In [176]:
a * b                                 # Multiplicacion de dos vectores
np.multiply(a, b)

array([[ 5],
       [12],
       [21],
       [28]])

In [177]:
a / b                                 # Division de vectores
np.divide(a, b)

array([[0.2       ],
       [0.33333333],
       [0.42857143],
       [0.57142857]])

In [168]:
np.log(a)                             # Logaritmo natural de un vector

array([[0.        ],
       [0.69314718],
       [1.09861229],
       [1.38629436]])

In [178]:
np.round(np.log(a))                   # Redondear los elementos de un vector

array([[0.],
       [1.],
       [1.],
       [1.]])

#### B. Operaciones vectoriales
Funciones del modulo numpy que operan sobre vectores.

In [244]:
v1 = np.array([1,4,6,3])               # Vector fila
print("Vector fila: ")
print(v1)

Vector fila: 
[1 4 6 3]


In [239]:
print("Sumatoria: ", v1.sum())         # Suma 

Sumatoria:  14


In [245]:
print("Media: ", v1.mean())            # Media

Media:  3.5


In [246]:
print("Varianza: ", v1.var())          # Varianza

Varianza:  3.25


In [248]:
print("Desv. estandar: ", v1.std())    # Desviacion estandar

Desv. estandar:  1.8027756377319946


In [249]:
print("Maximo: ", np.max(v1))          # Valor maximo

Maximo:  6


In [250]:
print("Minimo: ", np.min(v1))          # Valor minimo

Minimo:  1


In [269]:
# Producto interno/punto/escalar
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print("Producto interno: ", np.matmul(a1, a2))

# Alternativamene, se puede usar la funcion np.dot()
print("Producto interno: ", np.dot(a1, a2))

Producto interno:  32
Producto interno:  32


In [270]:
# Producto externo
np.outer(a1, a2)

# Es equivalente a la siguiente operacion
a1.reshape(1,3).transpose() * a2

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

#### C. Operaciones con matrices

In [283]:
A = np.random.rand(3,2)
B = np.random.rand(2,4)

print("Matriz A: ")
print(A)
print("\nMatriz B: ")
print(B)

Matriz A: 
[[0.29456251 0.73356772]
 [0.55385491 0.48131264]
 [0.38750591 0.92696382]]

Matriz B: 
[[0.81399665 0.46231692 0.32815725 0.88794081]
 [0.3969659  0.46158877 0.03232492 0.2181898 ]]


In [285]:
np.matmul(A, B)                         # Multiplicacion

array([[0.53097427, 0.47478785, 0.12037534, 0.42161107],
       [0.64190075, 0.478225  , 0.1973099 , 0.59680788],
       [0.68340154, 0.60702663, 0.15712691, 0.54633637]])

In [289]:
A1 = np.array([[1,2],                   # Matriz 3x2
               [3,4],
               [5,6]]); 
b1 = np.array([5,6,7]);                 # Vector 1x3

print("Matriz A1: ")
print(A1)
print("\nVector b1: ")
print(b1)

Matriz A1: 
[[1 2]
 [3 4]
 [5 6]]

Vector b1: 
[5 6 7]


In [295]:
# Multiplicacion vector-matriz

np.matmul(b1, A1)                      # La multiplicacion vector-matriz da como resultado un vector 1x2

array([58, 76])

In [296]:
c1 = np.array([[8, 9]]).T              # Vector 2x1 
print("Vector c1: ")
print(c1)

Vector c1: 
[[8]
 [9]]


In [299]:
# Multiplicacion matriz-vector
np.matmul(A1, c1)                      # La multiplicacion matriz-vector da como resultado un vector 3x1

array([[26],
       [60],
       [94]])

#### Las operaciones que forman parte del algebra lineal son mas eficientes en el modulo scipy.linalg

In [330]:
A2 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

print("Matriz A2: ")
print(A2)

Matriz A2: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [331]:
linalg.inv(A2)                          # Matriz inversa

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [332]:
linalg.eig(A2)[0]                       # Valores caracteristicos

array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -9.75918483e-16+0.j])

In [333]:
linalg.eig(A2)[1]                       # Vector caracteristico

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [315]:
linalg.svd(A2)[0]                       # Vector U

array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]])

In [318]:
U, S, V = linalg.svd(A2)                # Descomposicion de valor singular

print("Matriz U: ")
print(U)
print("\nMatriz S: ")
print(S)
print("\nMatriz V: ")
print(V)

Matriz U: 
[[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

Matriz S: 
[1.68481034e+01 1.06836951e+00 3.33475287e-16]

Matriz V: 
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]


#### D. Reshaping and assembling matrices

In [334]:
A3 = np.array([[1,2],                   # Matriz 3x2
               [3,4],
               [5,6]])

In [359]:
D = A3.reshape(A3.size, 1)              # Vector columna 6x1 a partir de los elementos de A3
print(D)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [363]:
D.sum()                                 # Suma de los elementos de A3 via el vector D

21

In [366]:
E = A3.reshape(2,3)                     # Matriz 2x3 a partir del vector D
print(E)

[[1 2 3]
 [4 5 6]]


In [385]:
c1 = np.array([1,2])                    # Vector fila 1x2
c2 = np.array([3,4])                    # Vector fila 1x2

c3 = np.hstack((c1, c2))                # Concatenacion de vectores c1 y c2

print("Concatenacion de c1 y c2: ", c3)

Concatenacion de c1 y c2:  [1 2 3 4]


In [390]:
d1 = np.array([[1],[2],[3]])            # Vector columna 3x1

d2 = np.vstack((d1, 4))
print("Concatenacion de d1 con 4:")
print(d2)

Concatenacion de d1 con 4:
[[1]
 [2]
 [3]
 [4]]


In [409]:
# Concatenacion horizontal de matrices
np.hstack((np.eye(3,3), np.random.randint(100, size=(3,3))))  

array([[ 1.,  0.,  0., 61.,  5., 79.],
       [ 0.,  1.,  0., 81., 62., 23.],
       [ 0.,  0.,  1., 69., 37., 25.]])

In [411]:
# Concatenacion vertical de matrices
np.vstack((np.eye(3,3), np.random.randint(100, size=(3,3))))  

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [23., 34., 53.],
       [70., 51., 45.],
       [62.,  0.,  6.]])

In [429]:
np.tile(5, (3, 2))                     # Matriz 3x2 de 5's

array([[5, 5],
       [5, 5],
       [5, 5]])

In [436]:
np.diag([1,2,3])                       # Matriz diagonal con los elementos del vector [1,2,3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])